/**
 * Test audio, generated rather than recorded.
 *
 * A copy of this lives in app-admin/test/tone.ts. The two apps are independent
 * builds with their own test runs, and both need a tone with a known melody: the
 * learner app feeds it to Chromium's fake microphone, the console cuts it into
 * segments. Ninety lines of pure arithmetic with no dependencies is the cheapest
 * thing in either tree to keep in two places.
 *
 * Synthesised speech-like tones with a known pitch contour.
 *
 * Scoring moved to the Python worker, so what is left for these is the studio's
 * cut proposal: speech-like bursts separated by silence, where the right
 * boundaries are known in advance. The parity fixtures the worker is checked
 * against are generated by a copy of this file in `scoring/reference/`.
 */

/** 8kHz: high enough for speech, and small enough to keep the tests quick. */
export const RATE = 8000

export interface ToneOptions {
  /** Semitones away from the base pitch, given progress through the clip (0..1). */
  melody?: (progress: number) => number
  baseHz?: number
  duration?: number
  /** Amplitude bumps standing in for syllables. */
  syllables?: number
  amplitude?: number
  /** Broadband noise as a fraction of amplitude. Real rooms are not silent,
      and a clean tone never makes the pitch tracker work for its answer. */
  noise?: number
  /** Fixed seed, so a noisy tone is the same tone every run. */
  seed?: number
}

export function tone({
  melody = () => 0,
  baseHz = 200,
  duration = 2.4,
  syllables = 4,
  amplitude = 0.25,
  noise = 0,
  seed = 1,
}: ToneOptions = {}): Float32Array {
  const count = Math.floor(RATE * duration)
  const samples = new Float32Array(count)
  let phase = 0
  const random = mulberry32(seed)
  for (let i = 0; i < count; i++) {
    const progress = i / count
    const hz = baseHz * 2 ** (melody(progress) / 12)
    phase += (2 * Math.PI * hz) / RATE
    // A few harmonics: a bare sine invites octave errors that speech does not.
    let value = 0
    for (let harmonic = 1; harmonic <= 6; harmonic++) value += Math.sin(phase * harmonic) / harmonic
    const envelope = Math.max(0.05, Math.abs(Math.sin(Math.PI * syllables * progress)) ** 1.5)
    samples[i] = value * amplitude * envelope + (noise ? (random() * 2 - 1) * amplitude * noise : 0)
  }
  return samples
}

/** A tiny deterministic generator: Math.random would make a fixture that
    changes every time it is written, which is not a fixture. */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export const MELODIES = {
  flat: () => 0,
  wide: (p: number) => Math.sin(p * Math.PI * 2) * 4,
  narrow: (p: number) => Math.sin(p * Math.PI * 2) * 1,
  rising: (p: number) => p * 4 - 2,
}

export function silence(duration = 1): Float32Array {
  return new Float32Array(Math.floor(RATE * duration))
}

/** Speech-like bursts separated by silence, as a recording of several lines is. */
export function lines(spec: { speech: number; pause: number; melody?: ToneOptions['melody'] }[]): Float32Array {
  const parts = spec.flatMap(({ speech, pause, melody = MELODIES.wide }) => [
    tone({ melody, duration: speech, syllables: Math.max(1, Math.round(speech * 2)) }),
    new Float32Array(Math.round(pause * RATE)),
  ])
  const total = parts.reduce((sum, part) => sum + part.length, 0)
  const out = new Float32Array(total)
  let offset = 0
  for (const part of parts) {
    out.set(part, offset)
    offset += part.length
  }
  return out
}
