/**
 * Writes the parity fixtures the Python worker is checked against.
 *
 * The worker replaces this TypeScript implementation. A take scored 82 here and
 * 74 there would make a learner's history incomparable across the switch, and
 * nothing in the app would show that it had happened — so the scores this code
 * produces today are frozen into files, and the port has to reproduce them.
 *
 * Run with: npx vitest run test/fixtures.gen.ts --mode fixtures
 * It is skipped in the normal suite; it writes files rather than asserting.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it } from 'vitest'
import { compareContours } from '../src/lib/dsp/compare'
import { trackPitch } from '../src/lib/dsp/pitch'
import { MELODIES, RATE, tone, type ToneOptions } from './tone'

const OUT = join(import.meta.dirname, '../../scoring/tests/fixtures')

/** 16-bit mono PCM WAV, which is what both implementations read. */
function wav(samples: Float32Array, rate: number): Buffer {
  const data = Buffer.alloc(samples.length * 2)
  for (let i = 0; i < samples.length; i++) {
    const clamped = Math.max(-1, Math.min(1, samples[i]))
    data.writeInt16LE(Math.round(clamped * 32767), i * 2)
  }
  const header = Buffer.alloc(44)
  header.write('RIFF', 0)
  header.writeUInt32LE(36 + data.length, 4)
  header.write('WAVE', 8)
  header.write('fmt ', 12)
  header.writeUInt32LE(16, 16)
  header.writeUInt16LE(1, 20)
  header.writeUInt16LE(1, 22)
  header.writeUInt32LE(rate, 24)
  header.writeUInt32LE(rate * 2, 28)
  header.writeUInt16LE(2, 32)
  header.writeUInt16LE(16, 34)
  header.write('data', 36)
  header.writeUInt32LE(data.length, 40)
  return Buffer.concat([header, data])
}

/** The cases cover every judgement the scorer makes, not just a happy path. */
const CASES: { name: string; reference: ToneOptions; take: ToneOptions }[] = [
  { name: 'identical', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide } },
  { name: 'octave-down', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, baseHz: 100 } },
  { name: 'monotone', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.flat } },
  { name: 'narrow-range', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.narrow } },
  { name: 'slow', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, duration: 3.6 } },
  { name: 'rising', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.rising } },
  { name: 'fewer-syllables', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, syllables: 2 } },
  { name: 'quiet', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, amplitude: 0.08 } },
  { name: 'low-voice-narrow', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.narrow, baseHz: 120 } },
  // Noise makes the tracker work for its answer: the cumulative-mean dips get
  // shallower, so the YIN threshold and the octave smoothing both come into
  // play, and a clean tone never exercises either.
  { name: 'noisy', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, noise: 0.12 } },
  { name: 'very-noisy', reference: { melody: MELODIES.wide }, take: { melody: MELODIES.wide, noise: 0.35 } },
  { name: 'noisy-both', reference: { melody: MELODIES.wide, noise: 0.25, seed: 7 }, take: { melody: MELODIES.narrow, noise: 0.4, seed: 9 } },
]

describe('parity fixtures', () => {
  it('writes the reference scores the Python worker must reproduce', () => {
    mkdirSync(OUT, { recursive: true })

    const manifest = CASES.map(({ name, reference, take }) => {
      const referenceSamples = tone(reference)
      const takeSamples = tone(take)
      writeFileSync(join(OUT, `${name}.reference.wav`), wav(referenceSamples, RATE))
      writeFileSync(join(OUT, `${name}.take.wav`), wav(takeSamples, RATE))

      const referenceContour = trackPitch(referenceSamples, RATE)
      const takeContour = trackPitch(takeSamples, RATE)
      const result = compareContours(referenceContour, takeContour)
      if (!result) throw new Error(`${name} produced no comparison`)

      return {
        name,
        score: result.score,
        scores: result.scores,
        meanDeviation: round(result.meanDeviation),
        // Carried so a parity failure says whether the pitch tracker or the
        // scoring drifted, rather than only that the total moved.
        referenceMedianHz: round(referenceContour.medianHz),
        takeMedianHz: round(takeContour.medianHz),
        referenceVoicedFrames: voiced(referenceContour),
        takeVoicedFrames: voiced(takeContour),
        duration: round(takeContour.duration),
      }
    })

    writeFileSync(
      join(OUT, 'expected.json'),
      JSON.stringify(
        {
          note: 'Generated by app/test/fixtures.gen.ts from the TypeScript scorer. Do not edit by hand.',
          analysisRate: RATE,
          cases: manifest,
        },
        null,
        2,
      ) + '\n',
    )
  })
})

const round = (v: number) => Math.round(v * 1e6) / 1e6
const voiced = (c: { frames: { hz: number | null }[] }) => c.frames.filter((f) => f.hz !== null).length
